name: Post Fact to Telegram (Debug)

on:
  workflow_dispatch:

jobs:
  post_fact:
    runs-on: ubuntu-latest

    steps:
      - name: 🧪 Debug runner
        run: echo "✅ Runner работает"

      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v4

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: 🧪 Проверим, что всё на месте
        run: ls -la

      - name: 🚀 Запускаем factbot.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python factbot.py
